version: '3.8'

services:
  db:
    container_name: aquele_database
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: lojadb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: